home/urls.py
from django.urls import path
from .views import index, about,books 

app_name = 'home'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('books/', books, name='books'),
]

selfWebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.


class Image(models.Model):
    Image = models.ImageField(upload_to='images/')

class HomePage(models.Model):
    Name = models.CharField(max_length=200)
    Email = models.EmailField(max_length=200)
    Mobile = models.CharField(max_length=200)
    Message = models.TextField()

    def __str__(self):
        return self.name

class OtherThing(models.Model):
    Heading = models.CharField(max_length=200,default="none",blank=True)
    Title = models.CharField(max_length=200,blank=True)
    File = models.FileField(upload_to="files/",blank=True)
    any_other_html = models.TextField(blank="True",default="none")
    any_image = models.ImageField(blank=True,upload_to="images/")

class Certificates(models.Model):
    certificate_html = models.TextField()

home/forms.py
from .models import HomePage
from django import forms


class SubscriberForm(forms.ModelForm):
    Name = forms.CharField(max_length=100,required=True, label='Name',widget=forms.Textarea(attrs={'rows':4, 'cols':40,'placeholder':"Name"} ))
    Email = forms.EmailField(max_length=100, required=True, label='Email',widget=forms.Textarea(attrs={'rows':4, 'cols':40,'placeholder':"Email"} )) 
    Mobile = forms.CharField(max_length=100, required=False, label='Mobile',widget=forms.Textarea(attrs={'rows':4, 'cols':40,'placeholder':"Mobile Ex. +919772328323"} )) 
    Message = forms.CharField(max_length=1000, required=False, label='Message',widget=forms.Textarea(attrs={'rows':4, 'cols':40,'placeholder':"Message"} )) 

    class Meta:
        model = HomePage
        fields = ['Name', 'Email', 'Mobile', 'Message']

home/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import SubscriberForm
from django.urls import reverse
from .utils import medium_blog, git_projects, send_simple_mail,send_django_mail
from .models import OtherThing,Image,Certificates


# Create your views here.


def index(request):
    form = SubscriberForm()
    image = Image.objects.all()
    if request.method == "POST":
        form = SubscriberForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            name = form.cleaned_data['Name']
            email = form.cleaned_data['Email']
            mobile = form.cleaned_data['Mobile']
            message = form.cleaned_data['Message']
            data = {
                'name': name,
                'email': email,
                'mobile': mobile,
                'message': message,
            }
            send_django_mail(data)
            form.save()
            return HttpResponseRedirect(reverse('home:index'))
        return render(request, 'index.html', {'form': form})
    blog = medium_blog(
        "https://api.rss2json.com/v1/api.json?rss_url=https://prabal-pathak.medium.com/feed")
    git_repos = git_projects(
        'https://api.github.com/users/prabal01pathak/repos')
    blog2 = ()
    context = {
        'form': form,
        'blogs': blog,
        'blogs2': blog2,
        'repos': git_repos,
    }
    return render(request, 'index.html', context)


def about(request):
    models = OtherThing.objects.all()
    image = Image.objects.all()
    if len(image) > 0:
        image = image[0]
    else:
        image=False
    certificates = Certificates.objects.all()
    context = {
            "otherThing":models,
            "image":image,
            "name": "Prabal Pathak",
            'certificates':certificates,

            }
    return render(request, 'about.html', context)

def books(requests):
    return render(requests, 'books.html')

home/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'about.css' %}">
<style>
    .testdome-certificate-stamp {
        margin: 2em;
        height: 500px;
    }
</style>
{% endblock %}

{% block title %}
    About Page 
{% endblock %}

{% block content %}
<main class="main-section">
<div class="about">
  <h1 class="about-name"><a href="#about" name="about">About</a></h1>

<!-- description Section -->
<div class="about-description">
	{% if  image %}
		<img src={{image.Image.url}} height=500px  />
	{% else %}
		<img src="{% static 'background1.jpg' %}" >
	{% endif %}
  <p>Hello, My name is Prabal Pathak,<br>
    I am a student of Computer Science and Engineering at the Rewa Engineering college.
    I am a passionate software Developer and I am currently working on my 3rd year project 
    I am always looking for new challenges to learn new things. 
    </p>
    </div>
</div>
<!-- end of description Section -->

  <h1 class="about-name"><a href="#about" name="about">CERTIFICATES</a></h1>

 {% for certificate in certificates %}
	 {{certificate.certificate_html|safe}}
 {% endfor %}


    <div class="about-skills">
    <h1 class="skills"><a href="#skills" name="skills">Skills</a></h1>
    <p>I have a good knowledge of the following languages and frameworks:<br>
    <div class="skills-list">
    <ul>
        <li>Python</li>
        <li>Django</li>
        <li>C++</li>
        <li>HTML</li>
        <li>CSS</li>
        <li>JavaScript</li>
        <li>Bootstrap</li>
        <li>jQuery</li>
        <li>MySQL</li>
        <li>Git</li>
        <li>GitHub</li>
    </ul>
    </div>
    </div>

    <div id="otherThing">
	    {% for things in otherThing %}
	    	  {% if things.Heading != "none" %}
		    <h1 class="about-name"><a href="#Resume" name="Resume">{{things.Heading}}</a></h1>
		    {% endif %}
		<div class="otherThing-link" style="margin: 2em;">
		{% if things.File %}
			<a href={{things.File.url}}>
			{{things.Title}}</a>
		{% endif %}
		</div>
		{% if things.any_other_html != "none" %}
			{{things.any_other_html|safe}}
		{% endif %}
		{% if things.any_image %}
			<img src={{things.any_image.url}} alt={{things.title}}>
		{% endif %}
			
	    {% endfor %}
    </div>

</main>
<div class="about-contact">
</div>

{% endblock %}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>{% block title %}{{setion.title}}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block links %}{{section.links}}{% endblock %}
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <header>
        <a href="{% url 'home:index' %}"><div class="logo">prabal's</div></a>
        <div class="header-links">
            <div class="home-link"><a href="{% url 'home:index' %}" name="home">home</a></div>
            <div class="about-link"><a href="{% url 'home:about' %}">about</a></div>
            <div class="contact-link"><a href="#contact">contact</a></div>
            <div class="github-link"><a href="https://www.github.com/prabal01pathak">github</a></div> 
        </div>
        <div class="menu-icon">
            <div class="icon1"></div>
            <div class="icon2"></div>
            <div class="icon3"></div>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="footer-links">
            <div class="home-link"><a href="{% url 'home:index' %}" name="home">Home</a></div>
            <div class="about-link"><a href="{% url 'home:about' %}">About</a></div>
            <div class="contact-link"><a href="#">Contact</a></div>
        </div>
        <div class="copyright">
            <p>&copy; prabal's</p>
        </div>
    </footer>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

home/templates/books.html
{% extends 'base.html' %}
{% block title  %}
    recomendation
{% endblock %}
{% block content %}
<h1> Books </h1>
<p> these are my recomendation</p>
{% endblock %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home Page{% endblock %}
{% block links %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}
{% block content %}
    <main>
        <div class="home-content">
            <img src="{% static 'background1.jpg' %}" alt="" width="100%" height="100%" >                
            <a href="{% url 'home:about' %}" class="btn">Know More</a>
            <div class="home-text">
                <h2>hi, i'm prabal</h2>
                <p>I'm a Software developer</p>
            </div>
        </div>
        <div class="Projects">
            <a href="#project" name="project"><h1 class="project-heading">PROJECTS.</h1></a>
            <ul>
                {% for r in repos %}
                <div class="project-title"> <a href={{r.0}} target="_blank"><li>{{r.1}}</li></a></div>
                {% endfor %}
            </ul>
            <div class="image-gallery">
                <img src="c:/users/hp/pictures/0photo.jpg" alt="new" />
            </div>
        </div>
            
        <div class="blog-posts">
            <h1><a href="#blog" name='blog'>Blog Posts</a></h1>
            <p class="learn-des">I love teaching and help people to learn something.
            I also love to write blog posts about my experiences and projects.
            </p>
            <h2>Some of my blog posts</h2>
                <div class="blog-title">
                    <ul>
                        {% for blog in blogs %}
                           <li> <a href={{blog.1}} target="_blank" ><img src={{blog.2|safe}} width="150px" height="100px" /><p>{{blog.0}}</p> </a></li>
                       {% endfor %}
                        {% for blog in blogs2 %}
                           <li> <a href={{blog.1}} target="_blank" ><img src={{blog.2|safe}} width="150px" height="100px" /><p>{{blog.0}}</p> </a></li>
                       {% endfor %}
                   <div class="blog-end"></div>
                   </ul>
                </div>
        </div>
        <div class="contact">
            <h1><a href="#contact" name="contact">Contact Me</a></h1>
            <div class="contact-content">
                <ul>
                    <li class="linkedin">
                        <a  href="https://www.linkedin.com/in/prabal-pathak-9a27451b6" target="_blank">
                            <img src="https://img.icons8.com/color/50/000000/linkedin.png" width=50px height=50px alt='linkedin'/>
                        </a>
                    </li>
                    <li class="github">
                        <a href="https://www.github.com/prabal01pathak" target="_blank">
                            <img src="https://img.icons8.com/ios-filled/50/000000/github.png" width=50px height=50px alt='github'/>
                        </a>
                    </li>
                    <li class="facebook">
                        <a href="https://www.facebook.com/Prabal.pathak11" target="_blank">
                            <img src="https://img.icons8.com/color/48/000000/facebook-new.png" widht=50px height=50px alt='facebook'/> 
                        </a>
                    </li>
                    <li class="twitter"> 
                        <a href="https://www.twitter.com/PrabalP56179978" target="blank">
                            <img src="https://img.icons8.com/fluency/48/000000/twitter.png" width=50px height=50px alt='twitter'/>
                        </a>
                    </li>
                    <li class="medium">
                        <a href="https://prabal-pathak.medium.com/" target="_blank">
                            <img src="https://img.icons8.com/ios-filled/50/000000/medium-monogram--v1.png" width='50px' height='50px' alt='medium'/>
                        </a>
                    </li>
                    
                </ul>
            </div>
                    
        <div class="subscribe-form">
            <form method="POST" action="{% url 'home:index' %}" class="sbuscriber-form">{% csrf_token %}
                <div class="form-name">
                    {{form.Name.errors}}
                    {{form.Name.label_tag}}
                    {{form.Name}}
                </div>
                <div class="form-email">
                    {{form.Email.errors}}
                    {{form.Email.label_tag}}
                    {{form.Email}}
                </div>
                <div class="form-mobile">
                    {{form.Mobile.errors}}
                    {{form.Mobile.label_tag}}
                    {{form.Mobile}}
                </div>
                <div class="form-message">
                    {{form.Message.errors}}
                    {{form.Message.label_tag}}
                    {{form.Message}}
                </div>
                <div class="form-submit">
                    <input type='submit' value='Send'>
                </div>
            </form>
            
        </div>
        
    </main>
{% endblock %}